using System.Collections.Generic;

namespace NNT_Archipealgo
{
    internal class MudokonTable
    {
        public static Dictionary<int, string> MudokonIDs = new()
        {
            {1, "Rupture Farms Escape ~ Secret Area 1 - Mudokon 1"},
            {2, "Rupture Farms Escape ~ Secret Area 1 - Mudokon 2"},
            {3, "Rupture Farms Escape ~ Secret Area 1 - Mudokon 3"},
            {4, "Rupture Farms Escape ~ Secret Area 2 - Mudokon 1"},
            {5, "Rupture Farms Escape ~ Secret Area 2 - Mudokon 2"},
            {6, "Rupture Farms Escape ~ Interactable Tutorial - Mudokon 1"},
            {7, "Rupture Farms Escape ~ Secret Area 3 - Mudokon 1"},
            {8, "Rupture Farms Escape ~ Secret Area 3 - Mudokon 2"},
            {9, "Rupture Farms Escape ~ Interactable Tutorial - Mudokon 2"},
            {10, "Rupture Farms Escape ~ Secret Area 4 - Mudokon 1"},
            {11, "Rupture Farms Escape ~ GameSpeak Tutorial - Mudokon 1"},
            {12, "Rupture Farms Escape ~ Bottlecap Tutorial - Mudokon 1"},
            {13, "Rupture Farms Escape ~ Secret Area 5 - Mudokon 1"},
            {14, "Rupture Farms Escape ~ Secret Area 5 - Mudokon 2"},
            {15, "Rupture Farms Escape ~ Secret Area 5 - Mudokon 3"},
            {16, "Rupture Farms Escape ~ Bottlecap Tutorial - Mudokon 2"},
            {17, "Rupture Farms Escape ~ Shadow Tutorial - Mudokon 1"},
            {18, "Rupture Farms Escape ~ Grinder Tutorial Mudokon"},
            {19, "Rupture Farms Escape ~ Shadow Tutorial - Mudokon 2"},
            {20, "Rupture Farms Escape ~ Zulag 2 Access - Mudokon 1"},
            {21, "Rupture Farms Escape ~ Zulag 2 Access - Mudokon 2"},
            {22, "Rupture Farms Escape ~ Zulag 2 Train Terminal Mudokon"},
            {23, "Rupture Farms Escape ~ Zulag 2 Access - Mudokon 3"},
            {24, "Rupture Farms Escape ~ Zulag 2 Access - Mudokon 4"},
            {25, "Rupture Farms Escape ~ Zulag 2 Access - Mudokon 5"},
            {26, "Rupture Farms Escape ~ Secret Area 6 - Mudokon 1"},
            {27, "Rupture Farms Escape ~ Secret Area 6 - Mudokon 2"},
            {28, "Rupture Farms Escape ~ Secret Area 6 - Mudokon 3"},
            {29, "Stockyards ~ Introduction Mudokon"},
            {30, "Stockyards ~ Secret Area - Mudokon 1"},
            {31, "Stockyards ~ Secret Area - Mudokon 2"},
            {32, "Free Fire Zone ~ Secret Area 4 - Mudokon 1"},
            {33, "Free Fire Zone ~ Secret Area 4 - Mudokon 2"},
            {34, "Free Fire Zone ~ Secret Area 1 - Mudokon 1"},
            {35, "Free Fire Zone ~ Secret Area 3 - Mudokon 1"},
            {36, "Free Fire Zone ~ Secret Area 3 - Mudokon 2"},
            {37, "Free Fire Zone ~ Secret Area 1 - Mudokon 2"},
            {38, "Free Fire Zone ~ Secret Area 2 - Mudokon 1"},
            {39, "Free Fire Zone ~ Secret Area 5 - Mudokon 1"},
            {40, "Free Fire Zone ~ Secret Area 6 - Mudokon 1"},
            {41, "Paramonian Trial 5 ~ Secret Area - Mudokon 1"},
            {42, "Paramonian Trial 5 ~ Secret Area - Mudokon 2"},
            {43, "Paramonian Trial 5 ~ Secret Area - Mudokon 3"},
            {44, "Scrabanian Temple Entrance ~ Secret Area - Mudokon 1"},
            {45, "Scrabanian Temple Entrance ~ Secret Area - Mudokon 2"},
            {46, "Scrabanian Trial 7 ~ Secret Area - Mudokon 1"},
            {47, "Scrabanian Trial 8 ~ Secret Area - Mudokon 1"},
            {48, "Scrabanian Trial 8 ~ Secret Area - Mudokon 2"},
            {49, "Scrabanian Trial 8 ~ Secret Area - Mudokon 3"},
            {50, "Zulag 1 ~ Entrance - Mudokon 1"},
            {51, "Zulag 1 ~ Zulag 2 Access - Mudokon 1"},
            {52, "Zulag 1 ~ Zulag 2 Access - Mudokon 2"},
            {53, "Zulag 1 ~ Shadow Tutorial - Mudokon 1"},
            {54, "Zulag 1 ~ Grinder Tutorial Mudokon"},
            {55, "Zulag 1 ~ Shrykull Portal Tutorial - Mudokon 1"},
            {56, "Zulag 1 ~ Shrykull Portal Tutorial - Mudokon 2"},
            {57, "Zulag 1 ~ Secret Area 1 - Mudokon 1"},
            {58, "Zulag 1 ~ Secret Area 1 - Mudokon 2"},
            {59, "Zulag 1 ~ Secret Area 1 - Mudokon 3"},
            {60, "Zulag 1 ~ GameSpeak Tutorial - Mudokon 1"},
            {61, "Zulag 1 ~ GameSpeak Tutorial - Mudokon 2"},
            {62, "Zulag 1 ~ Secret Area 2 - Mudokon 1"},
            {63, "Zulag 1 ~ Secret Area 2 - Mudokon 2"},
            {64, "Zulag 1 ~ Interactables Tutorial - Mudokon 1"},
            {65, "Zulag 1 ~ Interactables Tutorial - Mudokon 2"},
            {66, "Zulag 1 ~ Secret Area 3 - Mudokon 1"},
            {67, "Zulag 1 ~ Secret Area 3 - Mudokon 2"},
            {68, "Zulag 1 ~ Secret Area 4 - Mudokon 1"},
            {69, "Zulag 1 ~ Secret Area 4 - Mudokon 2"},
            {70, "Zulag 1 ~ Backtrack End - Mudokon 1"},
            {71, "Zulag 1 ~ Backtrack End - Mudokon 2"},
            {72, "Zulag 1 ~ Backtrack End - Mudokon 3"},
            {73, "Zulag 1 ~ Secret Area 5 - Mudokon 1"},
            {74, "Zulag 1 ~ Secret Area 5 - Mudokon 2"},
            {75, "Zulag 2 ~ Door 1 - Mudokon 1"},
            {76, "Zulag 2 ~ Door 1 - Mudokon 2"},
            {77, "Zulag 2 ~ Door 1 - Mudokon 3"},
            {78, "Zulag 2 ~ Door 1 (Back Area) - Mudokon 1"},
            {79, "Zulag 2 ~ Door 1 (Back Area) - Mudokon 2"},
            {80, "Zulag 2 ~ Door 2 - Mudokon 1"},
            {81, "Zulag 2 ~ Door 2 - Mudokon 2"},
            {82, "Zulag 2 ~ Door 3 - Mudokon 1"},
            {83, "Zulag 1 ~ Entrance - Mudokon 2"},
            {84, "Zulag 3 ~ Door 1 - Mudokon 1"},
            {86, "Zulag 3 ~ Door 1 - Mudokon 2"},
            {87, "Zulag 3 ~ Door 1 - Mudokon 3"},
            {88, "Zulag 3 ~ Door 1 (Back Area) - Mudokon 1"},
            {89, "Zulag 3 ~ Door 1 (Back Area) - Mudokon 2"},
            {90, "Zulag 3 ~ Door 2 - Mudokon 1"},
            {91, "Zulag 3 ~ Door 3 - Mudokon 1"},
            {92, "Zulag 3 ~ Door 3 (Back Area) - Mudokon 1"},
            {93, "Zulag 3 ~ Door 3 (Back Area) - Mudokon 2"},
            {94, "Zulag 4 ~ Slig Path - Mudokon 1"},
            {95, "Zulag 4 ~ Slig Path - Mudokon 2"},
            {96, "Zulag 4 ~ Slig Path (Post Boom Machine) - Mudokon 1"},
            {97, "Zulag 4 ~ Slig Path (Post Boom Machine) - Mudokon 2"},
            {98, "Zulag 4 ~ Slig Path (Post Boom Machine) - Mudokon 3"},
            {100, "Rupture Farms Escape ~ Secret Area 1 - Mudokon 4"},
            {101, "Rupture Farms Escape ~ Secret Area 1 - Mudokon 5"},
            {102, "Rupture Farms Escape ~ Secret Area 1 - Mudokon 6"},
            {103, "Rupture Farms Escape ~ Secret Area 1 - Mudokon 7"},
            {104, "Rupture Farms Escape ~ Secret Area 1 - Mudokon 8"},
            {105, "Rupture Farms Escape ~ Secret Area 1 - Mudokon 9"},
            {106, "Rupture Farms Escape ~ Secret Area 2 - Mudokon 3"},
            {107, "Rupture Farms Escape ~ Secret Area 2 - Mudokon 4"},
            {108, "Rupture Farms Escape ~ Secret Area 2 - Mudokon 5"},
            {109, "Rupture Farms Escape ~ Secret Area 2 - Mudokon 6"},
            {110, "Rupture Farms Escape ~ Secret Area 2 - Mudokon 7"},
            {111, "Rupture Farms Escape ~ Secret Area 2 - Mudokon 8"},
            {112, "Rupture Farms Escape ~ Secret Area 2 - Mudokon 9"},
            {113, "Rupture Farms Escape ~ Secret Area 3 - Mudokon 3"},
            {114, "Rupture Farms Escape ~ Secret Area 3 - Mudokon 4"},
            {115, "Rupture Farms Escape ~ Secret Area 3 - Mudokon 5"},
            {116, "Rupture Farms Escape ~ Secret Area 3 - Mudokon 6"},
            {117, "Rupture Farms Escape ~ Secret Area 3 - Mudokon 7"},
            {118, "Rupture Farms Escape ~ Secret Area 3 - Mudokon 8"},
            {119, "Rupture Farms Escape ~ Secret Area 4 - Mudokon 2"},
            {120, "Rupture Farms Escape ~ Secret Area 4 - Mudokon 3"},
            {121, "Rupture Farms Escape ~ Secret Area 4 - Mudokon 4"},
            {122, "Rupture Farms Escape ~ Secret Area 4 - Mudokon 5"},
            {123, "Rupture Farms Escape ~ Secret Area 4 - Mudokon 6"},
            {124, "Rupture Farms Escape ~ Secret Area 4 - Mudokon 7"},
            {125, "Rupture Farms Escape ~ Secret Area 4 - Mudokon 8"},
            {126, "Rupture Farms Escape ~ GameSpeak Tutorial - Mudokon 2"},
            {127, "Rupture Farms Escape ~ GameSpeak Tutorial - Mudokon 3"},
            {128, "Rupture Farms Escape ~ GameSpeak Tutorial - Mudokon 4"},
            {129, "Rupture Farms Escape ~ Secret Area 5 - Mudokon 4"},
            {130, "Rupture Farms Escape ~ Secret Area 5 - Mudokon 5"},
            {131, "Rupture Farms Escape ~ Secret Area 5 - Mudokon 6"},
            {132, "Rupture Farms Escape ~ Secret Area 5 - Mudokon 7"},
            {133, "Rupture Farms Escape ~ Secret Area 5 - Mudokon 8"},
            {134, "Rupture Farms Escape ~ Secret Area 6 - Mudokon 4"},
            {135, "Rupture Farms Escape ~ Secret Area 6 - Mudokon 5"},
            {136, "Rupture Farms Escape ~ Secret Area 6 - Mudokon 6"},
            {137, "Rupture Farms Escape ~ Secret Area 6 - Mudokon 7"},
            {138, "Stockyards ~ Secret Area - Mudokon 3"},
            {139, "Stockyards ~ Secret Area - Mudokon 4"},
            {140, "Stockyards ~ Secret Area - Mudokon 5"},
            {141, "Free Fire Zone ~ Secret Area 4 - Mudokon 3"},
            {142, "Free Fire Zone ~ Secret Area 4 - Mudokon 4"},
            {143, "Free Fire Zone ~ Secret Area 4 - Mudokon 5"},
            {144, "Free Fire Zone ~ Secret Area 3 - Mudokon 3"},
            {145, "Free Fire Zone ~ Secret Area 1 - Mudokon 3"},
            {146, "Free Fire Zone ~ Secret Area 1 - Mudokon 4"},
            {147, "Free Fire Zone ~ Secret Area 1 - Mudokon 5"},
            {148, "Free Fire Zone ~ Secret Area 1 - Mudokon 6"},
            {149, "Free Fire Zone ~ Secret Area 1 - Mudokon 7"},
            {150, "Free Fire Zone ~ Secret Area 1 - Mudokon 8"},
            {151, "Free Fire Zone ~ Secret Area 1 - Mudokon 9"},
            {152, "Free Fire Zone ~ Secret Area 2 - Mudokon 2"},
            {153, "Free Fire Zone ~ Secret Area 2 - Mudokon 3"},
            {154, "Free Fire Zone ~ Secret Area 6 - Mudokon 2"},
            {155, "Free Fire Zone ~ Secret Area 6 - Mudokon 3"},
            {156, "Free Fire Zone ~ Secret Area 6 - Mudokon 4"},
            {157, "Free Fire Zone ~ Secret Area 6 - Mudokon 5"},
            {158, "Free Fire Zone ~ Secret Area 6 - Mudokon 6"},
            {159, "Free Fire Zone ~ Secret Area 6 - Mudokon 7"},
            {160, "Free Fire Zone ~ Secret Area 5 - Mudokon 2"},
            {161, "Free Fire Zone ~ Secret Area 5 - Mudokon 3"},
            {162, "Free Fire Zone ~ Secret Area 5 - Mudokon 4"},
            {163, "Free Fire Zone ~ Secret Area 5 - Mudokon 5"},
            {164, "Free Fire Zone ~ Secret Area 5 - Mudokon 6"},
            {165, "Free Fire Zone ~ Secret Area 5 - Mudokon 7"},
            {166, "Free Fire Zone ~ Secret Area 5 - Mudokon 8"},
            {167, "Paramonian Trial 5 ~ Secret Area - Mudokon 4"},
            {168, "Paramonian Trial 5 ~ Secret Area - Mudokon 5"},
            {169, "Paramonian Trial 5 ~ Secret Area - Mudokon 6"},
            {170, "Paramonian Trial 5 ~ Secret Area - Mudokon 7"},
            {171, "Paramonian Trial 5 ~ Secret Area - Mudokon 8"},
            {172, "Paramonian Trial 5 ~ Secret Area - Mudokon 9"},
            {173, "Scrabanian Temple Entrance ~ Secret Area - Mudokon 3"},
            {174, "Scrabanian Temple Entrance ~ Secret Area - Mudokon 4"},
            {175, "Scrabanian Trial 7 ~ Secret Area - Mudokon 2"},
            {176, "Scrabanian Trial 7 ~ Secret Area - Mudokon 3"},
            {177, "Scrabanian Trial 7 ~ Secret Area - Mudokon 4"},
            {178, "Scrabanian Trial 7 ~ Secret Area - Mudokon 5"},
            {179, "Scrabanian Trial 8 ~ Secret Area - Mudokon 4"},
            {180, "Scrabanian Trial 8 ~ Secret Area - Mudokon 5"},
            {181, "Scrabanian Trial 8 ~ Secret Area - Mudokon 6"},
            {182, "Zulag 1 ~ Shadow Tutorial - Mudokon 2"},
            {183, "Zulag 1 ~ Shadow Tutorial - Mudokon 3"},
            {184, "Zulag 1 ~ Zulag 2 Access - Mudokon 3"},
            {185, "Zulag 1 ~ Zulag 2 Access - Mudokon 4"},
            {186, "Zulag 1 ~ Shadow Tutorial - Mudokon 4"},
            {187, "Zulag 1 ~ Shrykull Portal Tutorial - Mudokon 3"},
            {188, "Zulag 1 ~ Shrykull Portal Tutorial - Mudokon 4"},
            {189, "Zulag 1 ~ Shrykull Portal Tutorial - Mudokon 5"},
            {190, "Zulag 1 ~ Shrykull Portal Tutorial - Mudokon 6"},
            {191, "Zulag 1 ~ GameSpeak Tutorial - Mudokon 3"},
            {192, "Zulag 1 ~ GameSpeak Tutorial - Mudokon 4"},
            {193, "Zulag 1 ~ GameSpeak Tutorial - Mudokon 5"},
            {194, "Zulag 1 ~ GameSpeak Tutorial - Mudokon 6"},
            {195, "Zulag 1 ~ GameSpeak Tutorial - Mudokon 7"},
            {196, "Zulag 1 ~ Secret Area 1 - Mudokon 4"},
            {197, "Zulag 1 ~ Secret Area 1 - Mudokon 5"},
            {198, "Zulag 1 ~ Secret Area 1 - Mudokon 6"},
            {199, "Zulag 1 ~ Interactables Tutorial - Mudokon 3"},
            {200, "Zulag 1 ~ Interactables Tutorial - Mudokon 4"},
            {201, "Zulag 1 ~ Interactables Tutorial - Mudokon 5"},
            {202, "Zulag 1 ~ Backtrack End - Mudokon 4"},
            {203, "Zulag 1 ~ Backtrack End - Mudokon 5"},
            {204, "Zulag 1 ~ Backtrack End - Mudokon 6"},
            {205, "Zulag 1 ~ Backtrack End - Mudokon 7"},
            {206, "Zulag 1 ~ Entrance - Mudokon 3"},
            {207, "Zulag 1 ~ Backtrack End - Mudokon 8"},
            {208, "Zulag 1 ~ Backtrack End - Mudokon 9"},
            {209, "Zulag 1 ~ Secret Area 2 - Mudokon 3"},
            {210, "Zulag 1 ~ Secret Area 2 - Mudokon 4"},
            {211, "Zulag 1 ~ Secret Area 2 - Mudokon 5"},
            {212, "Zulag 1 ~ Secret Area 2 - Mudokon 6"},
            {213, "Zulag 1 ~ Secret Area 2 - Mudokon 7"},
            {214, "Zulag 1 ~ Secret Area 2 - Mudokon 8"},
            {215, "Zulag 1 ~ Secret Area 3 - Mudokon 3"},
            {216, "Zulag 1 ~ Secret Area 3 - Mudokon 4"},
            {217, "Zulag 1 ~ Secret Area 3 - Mudokon 5"},
            {218, "Zulag 1 ~ Secret Area 3 - Mudokon 6"},
            {219, "Zulag 1 ~ Secret Area 3 - Mudokon 7"},
            {220, "Zulag 1 ~ Secret Area 3 - Mudokon 8"},
            {222, "Zulag 1 ~ Secret Area 4 - Mudokon 3"},
            {223, "Zulag 1 ~ Secret Area 4 - Mudokon 4"},
            {226, "Zulag 1 ~ Secret Area 5 - Mudokon 3"},
            {227, "Zulag 1 ~ Secret Area 5 - Mudokon 4"},
            {228, "Zulag 1 ~ Secret Area 5 - Mudokon 5"},
            {229, "Zulag 1 ~ Secret Area 5 - Mudokon 6"},
            {230, "Zulag 1 ~ Secret Area 5 - Mudokon 7"},
            {231, "Zulag 1 ~ Secret Area 5 - Mudokon 8"},
            {232, "Zulag 2 ~ Door 1 - Mudokon 4"},
            {233, "Zulag 2 ~ Door 1 - Mudokon 5"},
            {234, "Zulag 2 ~ Door 1 - Mudokon 6"},
            {235, "Zulag 2 ~ Door 1 - Mudokon 7"},
            {236, "Zulag 2 ~ Door 1 - Mudokon 8"},
            {237, "Zulag 2 ~ Door 1 - Mudokon 9"},
            {238, "Zulag 2 ~ Door 1 (Back Area) - Mudokon 3"},
            {239, "Zulag 2 ~ Door 1 (Back Area) - Mudokon 4"},
            {240, "Zulag 2 ~ Door 1 (Back Area) - Mudokon 5"},
            {241, "Zulag 2 ~ Door 1 (Back Area) - Mudokon 6"},
            {242, "Zulag 2 ~ Door 3 - Mudokon 2"},
            {243, "Zulag 2 ~ Door 3 - Mudokon 3"},
            {244, "Zulag 2 ~ Door 3 - Mudokon 4"},
            {245, "Zulag 2 ~ Door 3 - Mudokon 5"},
            {246, "Zulag 2 ~ Door 3 - Mudokon 6"},
            {247, "Zulag 2 ~ Door 3 - Mudokon 7"},
            {248, "Zulag 2 ~ Door 3 - Mudokon 8"},
            {249, "Zulag 2 ~ Door 3 - Mudokon 9"},
            {250, "Zulag 2 ~ Door 2 - Mudokon 3"},
            {251, "Zulag 2 ~ Door 2 - Mudokon 4"},
            {252, "Zulag 2 ~ Door 2 - Mudokon 5"},
            {253, "Zulag 3 ~ Door 1 - Mudokon 4"},
            {254, "Zulag 3 ~ Door 1 - Mudokon 5"},
            {255, "Zulag 3 ~ Door 1 - Mudokon 6"},
            {256, "Zulag 3 ~ Door 1 - Mudokon 7"},
            {258, "Zulag 3 ~ Door 1 - Mudokon 8"},
            {259, "Zulag 3 ~ Door 1 - Mudokon 9"},
            {260, "Zulag 3 ~ Door 1 (Back Area) - Mudokon 3"},
            {261, "Zulag 3 ~ Door 1 (Back Area) - Mudokon 4"},
            {262, "Zulag 3 ~ Door 1 (Back Area) - Mudokon 5"},
            {263, "Zulag 4 ~ Secret Area 1 - Mudokon 1"},
            {264, "Zulag 4 ~ Secret Area 1 - Mudokon 2"},
            {265, "Zulag 4 ~ Secret Area 1 - Mudokon 3"},
            {266, "Zulag 3 ~ Door 2 - Mudokon 2"},
            {267, "Zulag 3 ~ Door 2 - Mudokon 3"},
            {268, "Zulag 3 ~ Door 2 - Mudokon 4"},
            {269, "Zulag 3 ~ Door 2 - Mudokon 5"},
            {270, "Zulag 3 ~ Door 3 - Mudokon 2"},
            {271, "Zulag 3 ~ Door 3 - Mudokon 3"},
            {272, "Zulag 3 ~ Door 3 - Mudokon 4"},
            {273, "Zulag 3 ~ Door 3 - Mudokon 5"},
            {274, "Zulag 3 ~ Door 3 - Mudokon 6"},
            {275, "Zulag 3 ~ Door 3 - Mudokon 7"},
            {276, "Zulag 3 ~ Door 3 - Mudokon 8"},
            {277, "Zulag 3 ~ Door 3 - Mudokon 9"},
            {278, "Zulag 3 ~ Door 3 (Back Area) - Mudokon 3"},
            {279, "Zulag 3 ~ Door 3 (Back Area) - Mudokon 4"},
            {280, "Zulag 3 ~ Door 3 (Back Area) - Mudokon 5"},
            {281, "Zulag 3 ~ Door 3 (Back Area) - Mudokon 6"},
            {282, "Zulag 3 ~ Door 3 (Back Area) - Mudokon 7"},
            {283, "Zulag 3 ~ Door 3 (Back Area) - Mudokon 8"},
            {284, "Zulag 4 ~ Slig Path - Mudokon 3"},
            {285, "Zulag 4 ~ Slig Path - Mudokon 4"},
            {286, "Zulag 4 ~ Slig Path - Mudokon 5"},
            {287, "Zulag 4 ~ Slig Path - Mudokon 6"},
            {288, "Zulag 4 ~ Slig Path - Mudokon 7"},
            {289, "Zulag 4 ~ Slig Path - Mudokon 8"},
            {290, "Zulag 4 ~ Slig Path - Mudokon 9"},
            {291, "Zulag 4 ~ Slig Path (Post Boom Machine) - Mudokon 4"},
            {292, "Zulag 4 ~ Slig Path (Post Boom Machine) - Mudokon 5"},
            {293, "Zulag 4 ~ Secret Area 2 - Mudokon 1"},
            {294, "Zulag 4 ~ Secret Area 2 - Mudokon 2"},
            {295, "Zulag 4 ~ Secret Area 2 - Mudokon 3"},
            {296, "Rupture Farms Escape ~ UXB Tutorial - Mudokon 1"},
            {297, "Rupture Farms Escape ~ UXB Tutorial - Mudokon 2"},
            {298, "Rupture Farms Escape ~ Shadow Tutorial - Mudokon 3"},
            {299, "Rupture Farms Escape ~ Shadow Tutorial - Mudokon 4"},
        };
    }
}
